<?xml version="1.0" encoding="UTF-8"  ?>


<!DOCTYPE Publications [
        <!ELEMENT Publications (Article)*>
        <!ELEMENT ArticleDantu (PubDetails)*>
        <!ATTLIST ArticleDantu
                PMID CDATA #REQUIRED>
        <!ELEMENT PubDetails (Journal|ArticleTitle|AuthorList)*>
        <!ELEMENT Journal (ISSN|JournalIssue|Title|ISOAbbreviation)*>
        <!ELEMENT ISSN (#PCDATA)>
        <!ATTLIST ISSN
                IssnType CDATA #REQUIRED>
        <!ELEMENT JournalIssue (Volume|Issue|PubDate)*>
        <!ATTLIST JournalIssue
                CitedMedium CDATA #REQUIRED>
        <!ELEMENT Volume (#PCDATA)>
        <!ELEMENT Issue (#PCDATA)>
        <!ELEMENT PubDate (Year|Month|Day)*>
        <!ELEMENT Year (#PCDATA)>
        <!ELEMENT Month (#PCDATA)>
        <!ELEMENT Title (#PCDATA)>
        <!ELEMENT ISOAbbreviation (#PCDATA)>
        <!ELEMENT ArticleTitle (#PCDATA)>
        <!ELEMENT AuthorList (Author)*>
        <!ATTLIST AuthorList
                CompleteYN CDATA #REQUIRED>
        <!ELEMENT Author (LastName|ForeName|Initials)*>
        <!ATTLIST Author
                ValidYN CDATA #REQUIRED>
        <!ELEMENT LastName (#PCDATA)>
        <!ELEMENT ForeName (#PCDATA)>
        <!ELEMENT Initials (#PCDATA)>
        <!ELEMENT Article (PubDetails)*>
        <!ATTLIST Article
                PMID CDATA #REQUIRED>
        <!ELEMENT Day (#PCDATA)>
        ]>
<Publications>
  <Article PMID="1">
    <PubDetails>
      <Journal>
        <ISSN IssnType="Print">0006-2944</ISSN>
        <JournalIssue CitedMedium="Print">
          <Volume>13</Volume>
          <Issue>2</Issue>
          <PubDate>
            <Year>1975</Year>
            <Month>Jun</Month>
          </PubDate>
        </JournalIssue>
        <Title>Biochemical medicine</Title>
        <ISOAbbreviation>Biochem Med</ISOAbbreviation>
      </Journal>
      <ArticleTitle>Formate assay in body fluids: application in methanol poisoning.</ArticleTitle>
      <AuthorList CompleteYN="Y">
        <Author ValidYN="Y">
          <LastName>Makar</LastName>
          <ForeName>A B</ForeName>
          <Initials>AB</Initials>
        </Author>
        <Author ValidYN="Y">
          <LastName>McMartin</LastName>
          <ForeName>K E</ForeName>
          <Initials>KE</Initials>
        </Author>
        <Author ValidYN="Y">
          <LastName>Palese</LastName>
          <ForeName>M</ForeName>
          <Initials>M</Initials>
        </Author>
        <Author ValidYN="Y">
          <LastName>Tephly</LastName>
          <ForeName>T R</ForeName>
          <Initials>TR</Initials>
        </Author>
      </AuthorList>
    </PubDetails>
  </Article>
  <Article PMID="2">
    <PubDetails>
      <Journal>
        <ISSN IssnType="Electronic">1090-2104</ISSN>
        <JournalIssue CitedMedium="Internet">
          <Volume>66</Volume>
          <Issue>4</Issue>
          <PubDate>
            <Year>1975</Year>
            <Month>Oct</Month>
            <Day>27</Day>
          </PubDate>
        </JournalIssue>
        <Title>Biochemical and biophysical research communications</Title>
        <ISOAbbreviation>Biochem Biophys Res Commun</ISOAbbreviation>
      </Journal>
      <ArticleTitle>Delineation of the intimate details of the backbone conformation of pyridine nucleotide coenzymes in aqueous solution.</ArticleTitle>
      <AuthorList CompleteYN="Y">
        <Author ValidYN="Y">
          <LastName>Bose</LastName>
          <ForeName>K S</ForeName>
          <Initials>KS</Initials>
        </Author>
              <Author ValidYN="Y">
          <LastName>Makar</LastName>
          <ForeName>A B</ForeName>
          <Initials>AB</Initials>
        </Author>
        <Author ValidYN="Y">
          <LastName>Sarma</LastName>
          <ForeName>R H</ForeName>
          <Initials>RH</Initials>
        </Author>
      </AuthorList>
    </PubDetails>
  </Article>
</Publications>
